EmiPlusPlusEvents.registerGroups((event) => {
  event.register("supplementaries:buntings", [
    Item.of("supplementaries:bunting", '{Color:"white"}'),
    Item.of("supplementaries:bunting", '{Color:"light_gray"}'),
    Item.of("supplementaries:bunting", '{Color:"gray"}'),
    Item.of("supplementaries:bunting", '{Color:"black"}'),
    Item.of("supplementaries:bunting", '{Color:"brown"}'),
    Item.of("supplementaries:bunting", '{Color:"red"}'),
    Item.of("supplementaries:bunting", '{Color:"orange"}'),
    Item.of("supplementaries:bunting", '{Color:"yellow"}'),
    Item.of("supplementaries:bunting", '{Color:"lime"}'),
    Item.of("supplementaries:bunting", '{Color:"green"}'),
    Item.of("supplementaries:bunting", '{Color:"cyan"}'),
    Item.of("supplementaries:bunting", '{Color:"light_blue"}'),
    Item.of("supplementaries:bunting", '{Color:"blue"}'),
    Item.of("supplementaries:bunting", '{Color:"purple"}'),
    Item.of("supplementaries:bunting", '{Color:"magenta"}'),
    Item.of("supplementaries:bunting", '{Color:"pink"}'),
  ]);

  event.register("supplementaries:bamboo_spikes", [
    "supplementaries:bamboo_spikes",
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"minecraft:poison"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"vintagedelight:strong_dehydrated"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"vintagedelight:long_dehydrated"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"vintagedelight:dehydrated"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"minecraft:long_weakness"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"minecraft:weakness"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"minecraft:strong_harming"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"minecraft:harming"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"minecraft:strong_slowness"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"minecraft:long_slowness"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"minecraft:slowness"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"minecraft:strong_poison"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"minecraft:long_poison"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"fyshisattribute:shorten_in_positive_potion"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"fyshisattribute:long_shorten_in_positive_potion"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"fyshisattribute:strong_shorten_in_positive_potion"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"fyshisattribute:extend_in_negative_potion"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"fyshisattribute:long_extend_in_negative_potion"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"fyshisattribute:strong_extend_in_negative_potion"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"ars_nouveau:blasting_potion"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"ars_nouveau:blasting_potion_long"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"ars_nouveau:blasting_potion_strong"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"ars_nouveau:freezing_potion"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"ars_nouveau:freezing_potion_long"}',
    ),
    Item.of(
      "supplementaries:bamboo_spikes_tipped",
      '{Damage:0,Potion:"ars_nouveau:freezing_potion_strong"}',
    ),
  ]);

  event.register("quark:quills", [
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:snowy_plains",targetBiomeColor:8381695,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:windswept_hills",targetBiomeColor:9079434,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:dark_forest",targetBiomeColor:22794,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:desert",targetBiomeColor:13416782,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:savanna",targetBiomeColor:10200418,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:swamp",targetBiomeColor:2242319,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:mangrove_swamp",targetBiomeColor:2242319,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:old_growth_pine_taiga",targetBiomeColor:5980703,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:flower_forest",targetBiomeColor:13518562,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:jungle",targetBiomeColor:2274816,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:bamboo_jungle",targetBiomeColor:4055575,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:badlands",targetBiomeColor:13008674,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:mushroom_fields",targetBiomeColor:5063283,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:ice_spikes",targetBiomeColor:2015433,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"minecraft:cherry_grove",targetBiomeColor:15313384,targetBiomeUnderground:0b}',
    ),
    Item.of(
      "quark:pathfinders_quill",
      '{targetBiome:"quark:glimmering_weald",targetBiomeColor:3241286,targetBiomeUnderground:0b}',
    ),
  ]);

  event.register("c:glazed_terracota", [
    "minecraft:white_glazed_terracotta",
    "minecraft:light_gray_glazed_terracotta",
    "minecraft:gray_glazed_terracotta",
    "minecraft:black_glazed_terracotta",
    "minecraft:brown_glazed_terracotta",
    "minecraft:red_glazed_terracotta",
    "minecraft:orange_glazed_terracotta",
    "minecraft:yellow_glazed_terracotta",
    "minecraft:lime_glazed_terracotta",
    "minecraft:green_glazed_terracotta",
    "minecraft:cyan_glazed_terracotta",
    "minecraft:light_blue_glazed_terracotta",
    "minecraft:blue_glazed_terracotta",
    "minecraft:purple_glazed_terracotta",
    "minecraft:magenta_glazed_terracotta",
    "minecraft:pink_glazed_terracotta",
  ]);

  event.register("tide:fish_buckets", [
    "tide:rainbow_trout_bucket",
    "tide:walleye_bucket",
    "tide:catfish_bucket",
    "tide:bluegill_bucket",
    "tide:guppy_bucket",
    "tide:pike_bucket",
    "tide:carp_bucket",
    "tide:yellow_perch_bucket",
    "tide:black_crappie_bucket",
    "tide:white_crappie_bucket",
    "tide:largemouth_bass_bucket",
    "tide:smallmouth_bass_bucket",
    "tide:brook_trout_bucket",
    "tide:flounder_bucket",
    "tide:arapaima_bucket",
    "tide:mirage_catfish_bucket",
    "tide:anchovy_bucket",
    "tide:tuna_bucket",
    "tide:sand_tiger_shark_bucket",
    "tide:slimy_salmon_bucket",
    "tide:mackerel_bucket",
    "tide:snook_bucket",
    "tide:frostbite_flounder_bucket",
    "tide:sturgeon_bucket",
    "tide:angelfish_bucket",
    "tide:mahi_mahi_bucket",
    "tide:blossom_bass_bucket",
    "tide:spore_stalker_bucket",
    "tide:sailfish_bucket",
    "tide:swordfish_bucket",
    "tide:mooneye_bucket",
    "tide:bull_shark_bucket",
    "tide:manta_ray_bucket",
    "tide:aquathorn_bucket",
    "tide:ocean_perch_bucket",
    "tide:red_snapper_bucket",
    "tide:neptune_koi_bucket",
    "tide:pluto_snail_bucket",
    "tide:sun_emblem_bucket",
    "tide:saturn_cuttlefish_bucket",
    "tide:marstilus_bucket",
    "tide:uranias_pisces_bucket",
    "tide:great_white_shark_bucket",
    "tide:shooting_starfish_bucket",
    "tide:coelacanth_bucket",
    "tide:cave_eel_bucket",
    "tide:cave_crawler_bucket",
    "tide:deep_grouper_bucket",
    "tide:shadow_snapper_bucket",
    "tide:chasm_eel_bucket",
    "tide:bedrock_tetra_bucket",
    "tide:gilded_minnow_bucket",
    "tide:crystalline_carp_bucket",
    "tide:luminescent_jellyfish_bucket",
    "tide:dripstone_darter_bucket",
    "tide:crystal_shrimp_bucket",
    "tide:lapis_lanternfish_bucket",
    "tide:iron_tetra_bucket",
    "tide:abyss_angler_bucket",
    "tide:anglerfish_bucket",
    "tide:glowfish_bucket",
    "tide:echo_snapper_bucket",
    "tide:devils_hole_pupfish_bucket",
    "tide:midas_fish_bucket",
    "tide:incandescent_larva_bucket",
    "tide:bedrock_bug_bucket",
    "tide:sleepy_carp_bucket",
    "tide:blue_neonfish_bucket",
    "tide:judgment_fish_bucket",
    "tide:deep_blue_bucket",
    "tide:nephrosilu_bucket",
    "tide:vengeance_bucket",
    "tide:pentapus_bucket",
    "tide:darkness_eater_bucket",
    "tide:shadow_shark_bucket",
    "tide:alpha_fish_bucket",
    "tide:magma_mackerel_bucket",
    "tide:ember_koi_bucket",
    "tide:ash_perch_bucket",
    "tide:obsidian_pike_bucket",
    "tide:volcano_tuna_bucket",
    "tide:inferno_guppy_bucket",
    "tide:warped_guppy_bucket",
    "tide:crimson_fangjaw_bucket",
    "tide:soulscale_bucket",
    "tide:witherfin_bucket",
    "tide:blazing_swordfish_bucket",
    "tide:pale_clubfish_bucket",
    "tide:amber_rockfish_bucket",
    "tide:enderfin_bucket",
    "tide:chorus_cod_bucket",
    "tide:ender_glider_bucket",
    "tide:endergazer_bucket",
    "tide:violet_carp_bucket",
    "tide:red_40_bucket",
    "tide:dutchman_sock_bucket",
    "tide:elytrout_bucket",
    "tide:mantyvern_bucket",
    "tide:snatcher_squid_bucket",
    "tide:voidseeker_bucket",
    "tide:dragon_fish_bucket",
  ]);

  event.register("quark:ancient_tomes", [
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:feather_falling",lvl:4s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:thorns",lvl:3s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:sharpness",lvl:3s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:smite",lvl:5s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:bane_of_arthropods",lvl:5s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:knockback",lvl:2s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:fire_aspect",lvl:2s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:looting",lvl:3s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:sweeping",lvl:3s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:efficiency",lvl:3s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:unbreaking",lvl:3s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:fortune",lvl:3s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:power",lvl:5s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:punch",lvl:2s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:luck_of_the_sea",lvl:3s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:lure",lvl:3s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:loyalty",lvl:3s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:impaling",lvl:5s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:riptide",lvl:3s}]}',
    ),
    Item.of(
      "quark:ancient_tome",
      '{StoredEnchantments:[{id:"minecraft:piercing",lvl:4s}]}',
    ),
  ]);
  event.register("fruitsdelight:jelly_bread", [
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["APPLE"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["BLUEBERRY"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["GLOWBERRY"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["HAMIMELON"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["MELON"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["HAWBERRY"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["LYCHEE"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["MANGO"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["KIWI"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["BAYBERRY"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["CHORUS"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["SWEETBERRY"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["MANGOSTEEN"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["CRANBERRY"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["LEMON"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["PINEAPPLE"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["PERSIMMON"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["PEAR"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["PEACH"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["ORANGE"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["FIG"]}'),
    Item.of("fruitsdelight:jelly_bread", '{JellyEffectRoot:["DURIAN"]}'),
  ]);
  event.register("wizardsreborn:arcane_enchanted_books", [
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:wissen_charge":2}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:life_mending":1}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:life_mending":2}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:eagle_shot":1}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:eagle_shot":2}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:life_mending":3}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:magic_blade":1}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:eagle_shot":3}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:eagle_shot":4}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:magic_blade":2}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:magic_blade":3}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:split":1}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:split":2}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:magic_blade":4}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:magic_blade":5}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:split":3}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:split":4}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:throw":1}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:life_roots":1}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:sonar":1}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:sonar":2}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:life_roots":2}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:wissen_charge":1}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:sonar":3}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:wissen_mending":3}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:wissen_mending":2}}',
    ),
    Item.of(
      "wizards_reborn:arcane_enchanted_book",
      '{arcaneEnchantments:{"wizards_reborn:wissen_mending":1}}',
    ),
  ]);

  event.register("wizardsreborn:alchemy_vials", [
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:water",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:milk",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:mundane_brew",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:alchemy_oil",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:oil_tea",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:wissen_tea",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:turtle_master",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:slowness",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:swiftness",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:fire_resistance",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:leaping",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:invisibility",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:night_vision",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:flower_brew",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:mor_brew",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:hellish_mushroom_brew",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:mushroom_brew",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:milk_tea",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:water_breathing",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:healing",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:harming",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:poison",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:regeneration",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:strength",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:weakness",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:luck",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:slow_falling",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:absorption",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:resistance",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:magical_attunement",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:darkness",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:honey",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:chocolate",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_vial_potion",
      '{alchemyPotion:"wizards_reborn:builders_tea",uses:0}',
    ),
  ]);
  event.register("wizardsreborn:alchemy_flaska", [
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:water",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:milk",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:mundane_brew",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:alchemy_oil",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:oil_tea",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:wissen_tea",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:milk_tea",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:mushroom_brew",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:healing",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:water_breathing",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:turtle_master",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:slowness",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:swiftness",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:fire_resistance",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:leaping",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:invisibility",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:night_vision",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:flower_brew",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:mor_brew",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:hellish_mushroom_brew",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:harming",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:poison",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:regeneration",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:strength",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:weakness",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:luck",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:slow_falling",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:absorption",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:resistance",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:magical_attunement",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:darkness",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:honey",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:chocolate",uses:0}',
    ),
    Item.of(
      "wizards_reborn:alchemy_flask_potion",
      '{alchemyPotion:"wizards_reborn:builders_tea",uses:0}',
    ),
  ]);
  event.register("wizardsreborn:engraved_wisestone", [
    "wizards_reborn:engraved_wisestone",
    "wizards_reborn:engraved_wisestone_lunam",
    "wizards_reborn:engraved_wisestone_vita",
    "wizards_reborn:engraved_wisestone_solem",
    "wizards_reborn:engraved_wisestone_mors",
    "wizards_reborn:engraved_wisestone_miraculum",
    "wizards_reborn:engraved_wisestone_praedictionem",
    "wizards_reborn:engraved_wisestone_degradatio",
    "wizards_reborn:engraved_wisestone_kara",
    "wizards_reborn:engraved_wisestone_lux",
    "wizards_reborn:engraved_wisestone_bellum",
    "wizards_reborn:engraved_wisestone_renaissance",
    "wizards_reborn:engraved_wisestone_fames",
    "wizards_reborn:engraved_wisestone_solstitium",
    "wizards_reborn:engraved_wisestone_siccitas",
    "wizards_reborn:engraved_wisestone_eclipsis",
    "wizards_reborn:engraved_wisestone_statera",
    "wizards_reborn:engraved_wisestone_tempus",
    "wizards_reborn:engraved_wisestone_evolutionis",
    "wizards_reborn:engraved_wisestone_tenebris",
    "wizards_reborn:engraved_wisestone_universum",
  ]);

  event.register(
    "limited_barrels_1",
    Ingredient.of(/sophisticatedstorage:limited.*barrel_1/).itemIds,
  );
  event.register(
    "limited_barrels_2",
    Ingredient.of(/sophisticatedstorage:limited.*barrel_2/).itemIds,
  );
  event.register(
    "limited_barrels_3",
    Ingredient.of(/sophisticatedstorage:limited.*barrel_3/).itemIds,
  );
  event.register(
    "limited_barrels_4",
    Ingredient.of(/sophisticatedstorage:limited.*barrel_4/).itemIds,
  );
  event.register(
    "sophisticated_chests",
    Ingredient.of(/sophisticatedstorage:.*chest/).itemIds,
  );
  event.register("shulker_boxes", Ingredient.of(/.*shulker_box.*/).itemIds);
  event.register("silt_shingles", Ingredient.of(/.*silt_shingles.*/).itemIds);
  event.register("counters", Ingredient.of(/.*counter.*/).itemIds);
});
