
[options]
	#Prevents Death by Teleporting Player to Spawn if trying to enter an Ender Portal
	preventdeath = false
	#Message that displays when Teleport is blocked
	blockedmessage = "Please obtain a %item% to enter the %dim%"
	#Title for the Advancements
	craftedmessage = "%dim% Unlocked!"
	#Description for the Advancements
	description = "Obtain a %item%"
	#Comma seperated list of items that when crafted unlock the corresponding dimension
	craftitems = "kubejs:nature_essence,thermal:steel_ingot,thermal:coal_coke,wizards_reborn:arcane_gold_ingot,immersiveengineering:ingot_steel"
	#Comma seperated list of Dimension Resource Names
	dimresname = "minecraft:the_nether,minecraft:the_end,twilightforest:twilight_forest,aether:the_aether,deeperdarker:otherside"
	#Comma seperated list of Dimension Display Names
	dimnames = "Nether,The End,Twilight Forest,Aether,Otherside"

