#IDs of inbuilt rulesets to enable. For example, "waystones:generated_waystones" makes all generated waystones breakable.
rulesets = ["waystones:generated_waystones"]
#List of custom rules with comma-separated parameters in parentheses. Conditions can be defined as comma-separated list in square brackets. Will be applied in order.
rules = []

