ServerEvents.recipes(event=>{
    
    const ArsRemoveById =[
        "looting_3",
        "looting_2",
        "looting_1",
        "protection_1",
        "protection_2",
        "protection_3",
        "protection_4",
        "protection_5",
        "blast_protection_1",
        "blast_protection_2",
        "blast_protection_3",
        "blast_protection_4",
        "blast_protection_5",
        "fire_protection_1",
        "fire_protection_2",
        "fire_protection_3",
        "fire_protection_4",
        "fire_protection_5",
        "projectile_protection_1",
        "projectile_protection_2",
        "projectile_protection_3",
        "projectile_protection_4",
        "projectile_protection_5",
        "reactive_1",
        "reactive_2",
        "reactive_3",
        "reactive_4",
        "feather_falling_1",
        "feather_falling_2",
        "feather_falling_3",
        "bane_of_arthropods_1",
        "bane_of_arthropods_2",
        "bane_of_arthropods_3",
        "bane_of_arthropods_4",
        "bane_of_arthropods_5",
        "smite_1",
        "smite_2",
        "smite_3",
        "smite_4",
        "smite_5",
        "sharpness_1",
        "sharpness_2",
        "sharpness_3",
        "sharpness_4",
        "sharpness_5",
        "mana_boost_1",
        "mana_boost_2",
        "mana_boost_3",
        "mana_regen_1",
        "mana_regen_2",
        "mana_regen_3",
        "unbreaking_1",
        "unbreaking_2",
        "unbreaking_3",
        "infinity_1",
        "piercing_1",
        "piercing_2",
        "piercing_3",
        "piercing_4",
        "piercing_5",
        "feather_falling_1",
        "feather_falling_2",
        "feather_falling_3",
        "feather_falling_4",
        "efficiency_1",
        "efficiency_2",
        "efficiency_3",
        "efficiency_4",
        "efficiency_5",
        "mending_1",
        "fortune_1",
        "fortune_2",
        "fortune_3",
        "looting_1",
        "looting_2",
        "looting_3",
        "flame_1",
        "respiration_1",
        "respiration_2",
        "respiration_3",
        "sweeping_1",
        "sweeping_2",
        "sweeping_3",
        "fire_aspect_1",
        "fire_aspect_2",
        "power_1",
        "power_2",
        "power_3",
        "power_4",
        "power_5",
        "knockback_1",
        "knockback_2",
        "quick_charge_1",
        "quick_charge_2",
        "quick_charge_3",
        "depth_strider_1",
        "depth_strider_2",
        "depth_strider_3",
        "punch_1",
        "punch_2",
        "thorns_1",
        "thorns_2",
        "thorns_3",
        "aqua_affinity_1",
        "multishot_1",
        "silk_touch_1"

    ]
    const WizardsRebornRemoveById =[
        "wizards_reborn:integration/farmers_delight/arcane_iterator/enchantments/backstabbing",
        "wizards_reborn:integration/create/arcane_iterator/enchantments/potato_recovery",
        "wizards_reborn:integration/create/arcane_iterator/enchantments/capacity",
        "wizards_reborn:arcane_iterator/enchantments/unbreaking",
        "wizards_reborn:arcane_iterator/enchantments/vanishing_curse",
        "wizards_reborn:arcane_iterator/enchantments/sweeping",
        "wizards_reborn:arcane_iterator/enchantments/thorns",
        "wizards_reborn:arcane_iterator/enchantments/silk_touch",
        "wizards_reborn:arcane_iterator/enchantments/smite",
        "wizards_reborn:arcane_iterator/enchantments/riptide",
        "wizards_reborn:arcane_iterator/enchantments/sharpness",
        "wizards_reborn:arcane_iterator/enchantments/quick_charge",
        "wizards_reborn:arcane_iterator/enchantments/respiration",
        "wizards_reborn:arcane_iterator/enchantments/quick_charge",
        "wizards_reborn:arcane_iterator/enchantments/protection",
        "wizards_reborn:arcane_iterator/enchantments/punch",
        "wizards_reborn:arcane_iterator/enchantments/power",
        "wizards_reborn:arcane_iterator/enchantments/projectile_protection",
        "wizards_reborn:arcane_iterator/enchantments/multishot",
        "wizards_reborn:arcane_iterator/enchantments/piercing",
        "wizards_reborn:arcane_iterator/enchantments/luck_of_the_sea",
        "wizards_reborn:arcane_iterator/enchantments/lure",
        "wizards_reborn:arcane_iterator/enchantments/looting",
        "wizards_reborn:arcane_iterator/enchantments/loyalty",
        "wizards_reborn:arcane_iterator/enchantments/infinity",
        "wizards_reborn:arcane_iterator/enchantments/knockback",
        "wizards_reborn:arcane_iterator/enchantments/frost_walker",
        "wizards_reborn:arcane_iterator/enchantments/impaling",
        "wizards_reborn:arcane_iterator/enchantments/flame",
        "wizards_reborn:arcane_iterator/enchantments/fortune",
        "wizards_reborn:arcane_iterator/enchantments/fire_aspect",
        "wizards_reborn:arcane_iterator/enchantments/fire_protection",
        "wizards_reborn:arcane_iterator/enchantments/efficiency",
        "wizards_reborn:arcane_iterator/enchantments/feather_falling",
        "wizards_reborn:arcane_iterator/enchantments/channeling",
        "wizards_reborn:arcane_iterator/enchantments/depth_strider",
        "wizards_reborn:arcane_iterator/enchantments/binding_curse",
        "wizards_reborn:arcane_iterator/enchantments/blast_protection",
        "wizards_reborn:arcane_iterator/enchantments/aqua_affinity",
        "wizards_reborn:arcane_iterator/enchantments/bane_of_arthropods"
    ]

    ArsRemoveById.forEach(id => {
		event.remove({id:"ars_nouveau:"+id})
	});

    WizardsRebornRemoveById.forEach(id => {
		event.remove({id:id})
	});

    event.custom({
        "type": "lychee:block_interacting",
        "hide_in_viewer": true,
        "post": [
            {
            "type": "prevent_default"
            }
        ],
        "item_in": {
            "type": "lychee:always_true"
        },
        "block_in": "minecraft:enchanting_table"
    })
    
})