
[creativeModeTabs]
	enableCreativeModeTabs = false
	syncSelectedCreativeModeTab = true
	disabledCreativeModeTabs = ["minecraft:op_blocks"]
	enableBerryTheme = true

[stackGroups]
	enableStackGroups = true
	enableCreateStackGroupButton = true

