
[creativeModeTabs]
	enableCreativeModeTabs = false
	syncSelectedCreativeModeTab = true
	disabledCreativeModeTabs = ["minecraft:op_blocks"]

[stackGroups]
	enableStackGroups = true
	disabledStackGroups = ["minecraft:head_armor", "minecraft:chest_armor", "minecraft:leg_armor", "minecraft:foot_armor", "minecraft:skulls", "minecraft:minecarts", "c:foods", "c:scrolls", "c:potions", "supplementaries:spikes", "minecraft:stone_buttons", "minecraft:wooden_buttons", "minecraft:copper_blocks"]

